# Menggunakan image Nginx untuk menjalankan web frontend
FROM nginx:alpine

# Menyalin file index.html Anda ke dalam folder server di container
COPY . /usr/share/nginx/html

# Membuka port 80 agar bisa diakses browser
EXPOSE 80